hotpotato/views/notifications/forms.py
from flask_wtf import FlaskForm


class AcknowledgeForm(FlaskForm):
    pass

hotpotato/api/web/v1/notifications/__init__.py
"""
Web API version 1 notification endpoints.
"""


from hotpotato.api.web.v1.notifications import get  # noqa: F401

hotpotato/api/web/v1/notifications/handlers/__init__.py
"""
Web API version 1 notification handler functions.
"""


from http import HTTPStatus

from flask import abort

from hotpotato.api.web.v1.notifications.handlers import (
    alerts as handler_alerts,
    handovers as handler_handovers,
    messages as handler_messages,
    notifications as handler_notifications,
)

_notif_handlers = {
    "notifications": handler_notifications,
    "alerts": handler_alerts,
    "handovers": handler_handovers,
    "messages": handler_messages,
}


def get(handler_name):
    """
    Return the notification handler for the given handler name.
    """

    if handler_name not in _notif_handlers:
        abort(HTTPStatus.NOT_FOUND)
    return _notif_handlers[handler_name]

hotpotato/notifications/__init__.py
"""
Notification constants and helper classes.
"""


import types

JSON_VERSION = 1


# A frozen set of values representing the type of a notification.
# NOTE: This list referenced by the Hot Potato database. If it is changed,
#       a new database migration will need to be created.
TYPE = frozenset(("alert", "handover", "message"))


# A frozen set of values representing the status of a notification.
STATUS = frozenset(
    (
        "NEW",
        "UNSENT",
        "SEND_FAILED",
        "SEND_FAILED_ACKNOWLEDGED",
        "SENDING",
        "SENT_TO_PROVIDER",
        "RECEIVED_BY_PROVIDER",
        "SENT_TO_CLIENT",
        "RECEIVED_BY_CLIENT",
        "READ_BY_CLIENT",
    )
)


# A frozen set of values representing verifiable sending methods.
VERIFIABLE_METHOD = frozenset(("app", "pushover"))

# A frozen set of values representing unverifiable sending methods.
UNVERIFIABLE_METHOD = frozenset(("pager", "sms"))

# A frozen set of values representing all possible sending methods for a notification.
METHOD = VERIFIABLE_METHOD | UNVERIFIABLE_METHOD


# A frozen set of values representing app notification sending providers.
APP_PROVIDER = frozenset()
# APP_PROVIDER = frozenset((
#    "app",
# ))

# A frozen set of values representing pager notification sending providers.
PAGER_PROVIDER = frozenset(("modica",))

# A frozen set of values representing SMS notification sending providers.
SMS_PROVIDER = frozenset(("modica", "twilio"))

# A frozen set of values representing Pushover notification sending providers.
PUSHOVER_PROVIDER = frozenset(("pushover",))

# A frozen set of values representing all possible sending providers for a notification.
PROVIDER = APP_PROVIDER | PAGER_PROVIDER | SMS_PROVIDER | PUSHOVER_PROVIDER

# A MappingProxyType (immutable rendering of a dict) object providing a mapping
# of possible sending providers for each method.
PROVIDER_FOR_METHOD = types.MappingProxyType(
    {
        "sms": SMS_PROVIDER,
        "pager": PAGER_PROVIDER,
        "app": APP_PROVIDER,
        "pushover": PUSHOVER_PROVIDER,
    }
)

hotpotato/notifications/queue/__init__.py
"""
Notification message queue functions.
"""


from hotpotato.notifications.queue.brokers import rabbitmq, stub


def init_app(app):
    """
    Initialise the notification message queue.
    """

    with app.app_context():
        test = False  # TODO: Incorporate FLASK_TESTING into this.
        if test:
            stub.init()
        else:
            rabbitmq.init()

hotpotato/notifications/senders/__init__.py
"""
Notification sender constants and helper classes.
"""


from flask import current_app

from hotpotato.notifications.senders import (
    pager_modica,
    pushover,
    sms_modica,
    sms_twilio,
)
from hotpotato.notifications.senders.debug_sender import DebugSender

APP = tuple()
# APP = ( # TODO: Hot Potato app
#    app.AppSender(),
# )

PUSHOVER = tuple((pushover.PushoverSender(),))

PAGER = tuple((pager_modica.ModicaPagerSender(),))

SMS = tuple((sms_modica.ModicaSMSSender(), sms_twilio.TwilioSMSSender()))

ALL = APP + PUSHOVER + PAGER + SMS


def for_method(method):
    """
    Return the possible senders for the given method.
    """

    if current_app.config["TESTING"]:
        return tuple((DebugSender(method),))
    else:
        if method == "app":
            return APP
        elif method == "pushover":
            return PUSHOVER
        elif method == "pager":
            return PAGER
        elif method == "sms":
            return SMS
        else:
            raise ValueError(method)

hotpotato/views/notifications/__init__.py
from hotpotato.views.notifications import views
from hotpotato.views.notifications._blueprint import blueprint

__all__ = ["views", "blueprint"]

hotpotato/views/notifications/_blueprint.py
"""
Notification views blueprint.
"""


import flask

blueprint = flask.Blueprint("views_notifications", __name__)

hotpotato/views/notifications/views.py
from http import HTTPStatus as Status

from flask import abort, flash, redirect, render_template, request, url_for
from flask_babelex import gettext as _
from flask_wtf import FlaskForm

from hotpotato import rules
from hotpotato.models import db
from hotpotato.notifications import (
    exceptions as notifications_exceptions,
    notifications,
)
from hotpotato.views._csrf import csrf
from hotpotato.views.notifications import functions
from hotpotato.views.notifications._blueprint import blueprint
from hotpotato.views.notifications.forms import AcknowledgeForm


@blueprint.route("/", methods=["GET"])
@rules.access_control_list(
    blueprint,
    rules.PermissionRule("notifications.get"),
    context=rules.contexts.team_and_escalates_to,
)
def notifications_get():
    """
    Display all notifications.
    """

    return functions.render_notifications_page()


@blueprint.route("/<notif_id>", methods=["GET"])
@rules.access_control_list(
    blueprint,
    rules.PermissionRule("notifications.get"),
    context=rules.contexts.team_and_escalates_to,
)
def notifications_get_by_id(notif_id):
    """
    Display information about a specific notifications.
    """

    form = AcknowledgeForm()

    try:
        return render_template(
            "notifications/get_by_id.html",
            notif=notifications.get(notif_id, eager=True),
            form=form,
        )

    except notifications_exceptions.NotificationIDError:
        return abort(Status.NOT_FOUND)


@blueprint.route("/acknowledge/<notif_id>", methods=["POST"])
@csrf.exempt
@rules.access_control_list(
    blueprint,
    rules.PermissionRule("notifications.acknowledge"),
    context=rules.contexts.team_and_escalates_to,
)
def acknowledge(notif_id):
    try:
        notif = notifications.get(notif_id)
    except notifications.exceptions.NotificationIDError:
        return abort(Status.NOT_FOUND)

    form = FlaskForm()
    if form.validate_on_submit():
        if notif.json["status"] != "SEND_FAILED":
            return abort(Status.BAD_REQUEST)

        notif.json["status"] = "SEND_FAILED_ACKNOWLEDGED"
        db.session.commit()

        flash("Notification acknowledged")

    if form.csrf_token.errors:
        flash(_("CSRF error, please try again"), "error")

    return redirect(
        request.referrer
        or url_for("views_notifications.notifications_get", **request.args)
    )

hotpotato/templates/notifications/display.html.j2
{% macro display_notifications(notifications, acknowledge_form, tags) %}
  {% set ns = namespace(date=None) %}
  {% set has_access_to_acknowledge = rules.has_access_to("views_notifications.acknowledge") %}
  {% for notif in notifications %}
    {% set notif_date = format_date(notif.received_dt, 'full') %}
    {% if notif_date != ns.date %}
      {% if ns.date %}
        {# Close the previous 'notif-group' tag #}
        </div>
      {% endif %}
      <div class="container notif-group">
        <div class="date">{{ notif_date }}</div>
      {% set ns.date = notif_date %}
    {% endif %}
    <div class="card-wrapper">
      {% if notif.notif_type == "alert" %}
      <a class="server-link" href="{{ notif.server.link }}"><img class="icon" src="{{ static_url_for('static', filename='img/icons/icon-external-link.svg') }}" alt=""></a>
      {% endif %}
      <a class="dropdown-toggle btn-icon no-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="icon" src="{{ static_url_for('static', filename='img/icons/icon-more.svg') }}" alt=""></a>
      <div class="dropdown-menu dropdown-menu-right dropdown-action" aria-labelledby="navbarDropdown">
        <a
          class="dropdown-item"
          href="{{ url_for('views_notifications.notifications_get_by_id', notif_id=notif.id) }}">
          Details
        </a>
        <button
          type="button"
          class="dropdown-item link-copy"
          data-clipboard-text="{{ request.url_root }}{{ url_for('views_notifications.notifications_get_by_id', notif_id=notif.id)[1:] }}">
          Copy link
        </a>
        <button
          type="button"
          class="dropdown-item link-copy"
          data-clipboard-text="{{ notif.body(user=current_user) }}">
          Copy summary
        </button>
        {% if notif.json['status'] == 'SEND_FAILED' and has_access_to_acknowledge %}
          <form
            action="{{url_for('views_notifications.acknowledge',
            notif_id=notif.id, **request.args)}}"
            method="POST">
            {{acknowledge_form.csrf_token}}
            <button class="text-danger dropdown-item">Acknowledge</button>
          </form>
        {% endif %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" data-toggle="collapse" href="#collapse{{ notif.id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
          Show raw data
        </a>
      </div>
      <div class="card{% if notif.is_critical or notif.failed_to_send() %} fire{% endif %}{%if notif.escalations|length != 0 %} danger{% endif %}">
        {{ render_notification_icon(notif) }}
        {{ render_notification_card(notif, tags) }}
        </div>
      </a>
    </div>
  {% endfor %}

  {% if ns.date %}
  {# Close the previous 'notif-group' tag #}
  </div>
  {% endif %}
{% endmacro %}

{% macro render_notification_icon(notif, link=True) %}
  {% if notif.notif_type == "alert" %}
    {% if notif.is_critical %}
      {% set title = "Critical Alert" %}
      {% set icon = static_url_for('static', filename='img/icons/icon-fire.svg') %}
    {% elif notif.json["state"] == "WARNING" %}
      {% set title = "Warning" %}
      {% set icon = static_url_for('static', filename='img/icons/icon-alert.svg') %}
    {% elif notif.json["state"] == "UP" or notif.json["state"] == "OK" %}
      {% set title = "Status update" %}
      {% set icon = static_url_for('static', filename='img/icons/icon-thumb-up.svg') %}
    {% else %}
      {% set title = "Alert" %}
      {% set icon = static_url_for('static', filename='img/icons/icon-alert.svg') %}
    {% endif %}
  {% elif notif.notif_type == "handover" %}
    {% set title = "Handover" %}
    {% set icon = static_url_for('static', filename='img/icons/icon-next.svg') %}
  {% elif notif.notif_type == "message" %}
    {% set title = "Message" %}
    {% set icon = static_url_for('static', filename='img/icons/icon-message.svg') %}
  {% else %}
    {% set title = "Notification" %}
    {% set icon = static_url_for('static', filename='img/icons/icon-message.svg') %}
  {% endif %}
  {% if link %}
  <a href="{{ url_for('views_notifications.notifications_get_by_id',
    notif_id=notif.id) }}" class="card-icon"
    data-toggle="tooltip" data-placement="top" title="{{ title }}">
  {% endif %}
    <img class="icon" src="{{ icon }}" alt="{{ title }}">
  {% if link %}
  </a>
  {% endif %}
{% endmacro %}

{% macro render_notification_title(notif) %}
  {% if notif.notif_type == "alert" %}
    {% if notif.json["service_name"] %}
      <span class="service">{{ notif.json["service_name"] }}</span>
      <span class="text-subtle"> on </span>
    {% endif %}
    <span class="hostname"{% if notif.json["display_name"] %} data-toggle="tooltip" data-placement="top" title="{{ notif.json["display_name"] }}"{% endif %}>
      {{ notif.json["hostname"] }}
    </span>
  {% elif notif.notif_type == "handover" %}
    {%- set to_user = notif.to_user -%}
    {%- set from_user = notif.from_user -%}
    {% if to_user %}
      <span class="tater-holder">{{ render_user(to_user, link=False) }}</span>
    {% else %}
      <span class="tater-holder">No one</span>
    {% endif %}
    {% if from_user %}
      <span class="text-subtle">has taken over the pager from</span>
      <span class="tater-giver">{{ render_user(from_user, link=False) }}</span>
    {% else %}
      <span class="text-subtle">has taken the pager</span>
    {% endif %}
  {% elif notif.notif_type == "message" %}
    {%- set from_user = notif.from_user -%}
    {% if from_user %}
      {{ render_user(from_user, link=False) }}
    {% else %}
      Hot Potato
      <span class="badge badge-secondary font-weight-normal">internal</span>
    {% endif %}
  {% else %}
  {% endif %}
  {% if notif.json["trouble_code"] and config.get('HOTPOTATO_TROUBLECODE_URL') -%}
    &mdash; <a href="{{ config.get('HOTPOTATO_TROUBLECODE_URL').format(trouble_code=notif.json['trouble_code']) }}">{{ notif.json["trouble_code"] }}</a>
  {%- endif -%}
{% endmacro %}

{% macro render_notification_card(notif, tags) %}
  {% set notif_time = format_datetime(notif.received_dt, "yyyy-MM-dd HH:mm" if current_user.use_24hr else "yyyy-MM-dd hh:mm a") %}
  {% set notif_dt = format_datetime(notif.received_dt, "yyyy-MM-dd HH:mm:ss Z") %}
  <div class="card-body" data-id="{{ notif.id }}" data-team-id="{{ notif.team.id }}">
    <div class="card-title">
      <h2 class="h6">{{render_notification_title(notif)}}</h2>
    </div>
    <div class="card-text">
      <div>
        <span class="time" data-toggle="tooltip" title="{{ notif_dt }}">{{ notif_time }}</span>
        <span class="message">
          {% set truncate_len = 500 %}
          {% set elipsis = render_elipsis(link=url_for('views_notifications.notifications_get_by_id', notif_id=notif.id)) %}
          {% if notif.notif_type == "alert" %}
            {% set hyphen = joiner(" - ") %}
            {% if notif.json['state'] %}
              {{ hyphen() }}
              <span data-toggle="tooltip" title="Status">{{ notif.json['state'] }}</span>
            {% endif %}
            {% if notif.json['output'] %}
              {{ hyphen() }}
              <span class="message">{{ notif.json['output']|truncate(truncate_len, end=elipsis) }}</span>
            {% endif %}
          {% elif notif.notif_type in ["handover", "message"] %}
            {% if notif.json['message'] %}
              {{ notif.json['message']|truncate(truncate_len, end=elipsis) }}
            {% else %}
              <i>(No message)</i>
            {% endif %}
          {% else %}
            {{ notif.body|truncate(truncate_len, end=elipsis) }}
          {% endif %}
        </span>
      </div>
      {% if notif.notif_type == "alert" and feature_tags %}
      <div class="d-flex flex-row">
        <span class="label-group d-inline-flex">
          {%- for tag in notif.tags -%}
            <a href="{{ util.add_query_args(tag=tag.name) }}" class="badge badge-secondary mr-1" data-id="{{ tag.id }}">{{ tag.name }}</a>
          {%- endfor -%}
        </span>
        <div class="btn-group">
      <button class="btn btn-secondary btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-label="Add tag">
        +<span class="caret"></span>
      </button>
      <div class="dropdown-menu tag-dropdown">
        {%- for tag in notif.team.tags -%}
        <a class="dropdown-item add-tag" href="#" data-id="{{ tag.id }}" data-added="{% if tag in notif.tags %}true{% else %}false{% endif %}">
          {{- tag.name -}}{%- if tag in notif.tags -%}
          <img class="icon" src="{{ static_url_for('static', filename='img/icons/icon-thumb-up.svg') }}" alt="">
          {%- endif -%}
        </a>
        {%- endfor -%}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{{ url_for('views_admin.manage_team', _team_id=notif.team.id) }}">Manage Tags</a>
      </div>
    </div>

      </div>
      {% endif %}
      <div class="delivery">
        <div>
          {% if notif.send_attempts|length == 0 %}
            Not yet sent
          {% elif notif.send_attempts|length == 1 %}
            {{render_status(notif.send_attempts[0])}}
          {% else %}
            {% set recipients = set(notif.send_attempts|map(attribute='user'))|length %}
            Sent {{notif.send_attempts|length}} times to {{recipients}} recipient{% if recipients > 1 %}s{% endif %}
          {% endif %}
        </div>
        {% if notif.escalations|length > 0 %}
          {% if notif.team_id != current_team.id %}
          <div>
            Escalated from {{notif.team.name}}
          </div>
          {% else %}
          <div>
            Escalated to {{ notif.escalations[0].escalated_to.name }}
          </div>
          {% endif %}
        {% endif %}
      </div>
    </div>
    <div class="accordion" id="accordionExample">
      <div class="collapse" id="collapse{{ notif.id }}">
        <hr />
        <code><pre class="mb-0">{{ notif.as_json(indent=2) }}</pre></code>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro render_notification_details(notif) %}
  <table class="table">
    <tbody>
      {% if notif.notif_type == "alert" %}
        {% if feature_tags %}
        <tr>
          <th>Tags</th>
          <td>
            <p>
              <span class="label-group">
                {%- for tag in notif.tags -%}
                  <a href="{{ url_for('views_notifications.notifications_get', tag=tag.name) }}" class="badge badge-secondary mr-1" data-id="{{ tag.id }}">{{ tag.name }}</a>
                {%- endfor -%}
              </span>
            </p>
          </td>
        </tr>
        {% endif %}
        <tr>
          <th>State</th>
          <td>{{notif.json["state"]}}</td>
        </tr>
        {% if notif.json["alert_type"] == "service" %}
          <tr>
            <th>Service</th>
            <td>{{notif.json["service_name"]}}</td>
          </tr>
        {% endif %}
        <tr>
          <th>Host</th>
          <td>{{notif.json["hostname"]}}</td>
        </tr>
        <tr>
          <th>Source</th>
          <td>{{notif.server.hostname}}</td>
        </tr>
        <tr>
          <th>Server time</th>
          <td>
            {{format_datetime(
              util.datetime_get_from_string(
                notif.json["timestamp"]
              ), "yyyy-MM-dd HH:mm:ss" if current_user.use_24hr else "yyyy-MM-dd hh:mm:ss a"
            )}}
          </td>
        </tr>
        <tr>
          <th>Output</th>
          <td>
            <textarea disabled class="form-control
            notif-message expanded">{{notif.json["output"]}}</textarea>
          </td>
        </tr>
      {% endif %}
      {% if "from_user_id" in notif.json and notif.json["from_user_id"] != None %}
        <tr>
          <th>From</th>
          <td>{{render_user(notif.from_user)}}</td>
        </tr>
      {% endif %}
      {% if "to_user_id" in notif.json and notif.json["to_user_id"] != None %}
        <tr>
          <th>To</th>
          <td>{{render_user(notif.to_user)}}</td>
        </tr>
      {% endif %}
      {% if notif.json["message"] %}
          <tr>
            <th>Message</th>
            <td><textarea disabled class="form-control notif-message expanded">{{notif.json["message"]}}</textarea></td>
          </tr>
      {% endif %}
    </tbody>
  </table>
{% endmacro %}

{% macro render_status(attempt) %}
  {% if attempt.has_been_received_by_client() %}
    Received by client
  {% elif attempt.has_been_sent() %}
    Sent
  {% elif attempt.failed_to_send() %}
    Send failed
    {% if attempt.send_failed_acknowledged() %}
      (Acknowledged)
    {% endif %}
  {% else %}
    Not yet sent
  {% endif %}
{% endmacro %}

{% macro render_user(user, link=False) %}
  {% if link %}
  <a href="#">
  {% endif %}
    {{ user.name }}
  {% if link %}
  </a>
  {% endif %}
{% endmacro %}

{% macro render_elipsis(link=False) -%}
  {% if link %}
  <a href="{{ link }}">
  {% endif %}
      &hellip;
  {% if link %}
  </a>
  {% endif -%}
{%- endmacro %}

hotpotato/templates/notifications/get.html
{% extends "base.html" %}

{% block body %}

{% include "modals/message.html" %}
{% include "modals/take.html" %}

<div class="header">
  <div class="container">
    <div class="page-title">
      <h1 class="h4">{{ heading }}</h1>
      {% if i_can_figure_out_this_condition %}
      <div class="page-title-meta">
        <img class="icon" src="{{ static_url_for('static', filename='img/icons/icon-fire.svg') }}" alt="">
        <p>1 critical notification in last hour</p>
      </div>
      {% endif %}
    </div>
    <div id="notif-actions" class="actions"> <!-- Actions menu -->
      <div class="assigned mr-auto">
        {% if not pagerperson.id %}
          {% trans %}The tater isn't held!{% endtrans %}
        {% elif pagerperson == current_user %}
          <div class="assignee">You</div> hold the tater
        {% else %}
          <div class="assignee"><a href="{{ url_for('views_users.get', user_id=pagerperson.id) }}">{{ pagerperson.name }}</a></div> holds the tater
        {% endif %}
      </div>
      {% if pagerperson.id and rules.has_access_to("views.send_message")  %}
        <div data-toggle="tooltip" data-placement="bottom" title="{% trans %}Message tater holder{% endtrans %}">
          <button id="message-tater-button" type="button" class="btn btn-lg btn-icon btn-outline-secondary" data-toggle="modal" data-target="#message-tater">
            <img class="icon" src="{{ static_url_for('static', filename='img/icons/icon-message-add.svg') }}" alt="">
          </button>
        </div>
      {% endif %}
      {% if rules.has_access_to("views.do_handover") %}
      <span
        class="d-inline-block"
        {% if no_contact_methods %}
          tabindex="0"
          data-toggle="tooltip"
          title="You cannot take the pager if you have no contact methods."
          {% endif %}>
        <button
          {% if
            pagerperson == current_user or
            no_contact_methods
          %}
            disabled
          {% endif %}
          type="button"
          class="btn btn-lg btn-primary btn-tater"
          data-toggle="modal"
          data-target="#take-tater">
          {% trans %}Take Tater{% endtrans %}
          <svg>
            <path id="btn-tater" d="M62.05 56C43.967 56 25.883 56 7.8 56C3.5 56 0 52.5 0 48.3C0 37.433 0 26.567 0 15.7C0 11.5 3.5 8 7.8 8C16.4 8 25 8 33.6 8C42.2 8 50.8 8 59.4 8C78.333 8 97.267 8 116.2 8C116.2 8 116.2 8 116.2 8C120.5 8 124 11.5 124.1 15.7C124.1 26.533 124.1 37.367 124.1 48.2C124.1 52.5 120.6 56 116.3 56C107.258 56 98.217 56 89.175 56L62.05 56"/>
          </svg>
        </button>
      </span>
      {% endif %}
    </div>
  </div>
</div>

<!-- Notification search filter -->
<!-- Filter mobile accordion toggle -->

{% if rules.has_access_to("views_notifications.notifications_get") %}
<div class="container filter-toggle">
  <button class="btn btn-sm btn-outline-secondary btn-block" type="button" data-target=".filters" data-toggle="collapse" >{% trans %}Filter notifications{% endtrans %}</button>
</div>

<div id="notif-filters" data-timezone="{{ current_user.timezone }}" data-use24hr="{{ current_user.use_24hr }}" class="filters collapse">
    <div class="container flex-wrap">
      <form method="get" class="form-inline flex-sm-grow-1" id="notification-filter-form">
        <input type="hidden" name="team_id" value="{{current_team.id}}">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><img class="icon icon-secondary" src="{{ static_url_for('static', filename='img/icons/icon-search.svg') }}" alt=""></span>
          </div>
          <input type="text" {% if 'body' in current_search_filters %}value="{{ current_search_filters['body'] }}" {% endif %}class="form-control" placeholder="{% trans %}Broken{% endtrans %}" aria-label="{% trans %}Filter notifications{% endtrans %}" data-toggle="tooltip" title="Additional filters currentely don't work, this is being fixed in https://gitlab.com/Hot-Potato/hotpotato/issues/100" />
        </div>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><img class="icon icon-secondary" src="{{ static_url_for('static', filename='img/icons/icon-calendar.svg') }}" alt=""></span>
          </div>
          <input type="date" {% if 'start_date' in current_search_filters %}value="{{ current_search_filters['start_date']|replace('Z', '+00:00') }}" {% endif %}name="start_date" class="form-control flat-datetime date-start" placeholder="dd/mm/yyyy" aria-label="{% trans %}Filter notifications{% endtrans %}" />
        </div>
        <div class="input-group input-range">
          <input type="date" {% if 'end_date' in current_search_filters %}value="{{ current_search_filters['end_date']|replace('Z', '+00:00') }}" {% endif %}name="end_date" class="form-control flat-datetime" placeholder="dd/mm/yyyy" aria-label="{% trans %}Filter notifications{% endtrans %}" />
        </div>
        <select
          name="status"
          class="form-control">
          <option value="">{% trans %}Any{% endtrans %}</option>
          {% for status in notifications.STATUS %}
            <option
            value="{{status}}"
            {% if 'status' in current_search_filters and
            current_search_filters['status'] == status %}
            selected
            {% endif %}
            >{{snake_to_sentence(status)}}</option>
          {% endfor %}
        </select>
        <div class="input-group">
          <button id="search-filters-apply" type="submit" class="btn btn-primary">{% trans %}Apply{% endtrans %}</button>
        </div>
      </form>
      <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" id="exportDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans %}Export{% endtrans %} <span class="caret"></span></button>
        <div class="dropdown-menu" aria-labelledby="exportDropdown">
          <a type="submit" href="{{ url_for('api_web_v1.notifications_get', **current_search_filters) }}" class="dropdown-item" id="notifications-export-as-json">{% trans %}As JSON{% endtrans %}</a>
          <a type="submit" href="{{ url_for('api_web_v1.notifications_get_as_csv', **current_search_filters) }}" class="dropdown-item" id="notifications-export-as-csv">{% trans %}As CSV{% endtrans %}</a>
        </div>
      </div>
    </div>
</div>

<!-- Notifications table -->

<div id="notifications">
  {% from "notifications/display.html.j2" import display_notifications %}
  {{ display_notifications(id_notif, acknowledge_form, tags) }}
</div>
{% else %}
<div class="container">
  <p>You don't have permission to access notifications.</p>
</div>
{% endif %}

{% endblock %}